Added the error text back in for invalid metric.
This was lost by accident when CPU was chosen by default.

diff --git a/sarplot b/sarplot
--- a/sarplot
+++ b/sarplot
@@ -60,6 +60,9 @@ then
         metric="-u"
         field=",8"
         title="CPU %Idle"
+else
+	echo "Invalid metric specified!"
+	exit 1
 fi
 
 #####################################
