Updated to allow specifying metric and date to plot via arguments -m and -d

diff --git a/sarplot b/sarplot
--- a/sarplot
+++ b/sarplot
@@ -4,6 +4,34 @@
 ## Hereward Cooper - 14/10/2009
 ## A hack to plot various system resource information from sar using gnuplot
 
+# Begin new option parsing code...
+usage="Usage: $0 [-m METRIC] [-d DAY]"
+metric=""
+sadate=""
+while getopts ":m:d:" options; do
+  case $options in
+    m ) metric=$OPTARG;;
+ d ) sadate=$OPTARG
+     if [ -d /var/log/sa ]; then
+      safile="/var/log/sa/sa$sadate"
+     else
+      if [ -d /var/log/sysstat ]; then
+       safile="/var/log/sysstat/sa$sadate"
+   fi
+  fi;;
+ : ) echo "Missing parameter to option: -$OPTARG"
+     echo $usage
+  exit 1;;
+    \? ) echo $usage
+         exit 1;;
+    * ) echo $usage
+          exit 1;;
+  esac
+done
+if [ "xxx${metric}yyy" == "xxxyyy" ]; then
+    metric="cpu"
+fi
+
 ## Start off doing some checks for required programs
 if [ ! -f /usr/bin/gnuplot ]
 then
@@ -26,7 +54,7 @@ fi
 #####################################################
 
 # Swap Usage
-if [[ $1 == "swap" ]]
+if [[ $metric == "swap" ]]
 then
         sar -r | grep swpused || echo "No Swap Detected"; exit 1
         metric="-r"
@@ -34,48 +62,48 @@ then
         title="% Swap Usage"
 
 # 1 Minute Load Average
-elif [[ $1 == "load" ]]
+elif [[ $metric == "load" ]]
 then
         metric="-q"
         field="ldavg-1"
         title="1 Minute Load Average"
 
 # Disk Read IO
-elif [[ $1 == "io" ]]
+elif [[ $metric == "io" ]]
 then
         metric="-b"
         field="rtps"
         title="Read Requests per Second"
 
 # Disk Write IO
-elif [[ $1 == "iow" ]]
+elif [[ $metric == "iow" ]]
 then
         metric="-b"
         field="wtps"
         title="Write Requests per Second"
 
 # Network Inbound
-elif [[ $1 == "netin" ]]
+elif [[ $metric == "netin" ]]
 then
         metric="-n DEV "
         field="eth0.*rxbyt"
         title="kB/s Recieved on eth0"
 
-elif [[ $1 == "ctx" ]]
+elif [[ $metric == "ctx" ]]
 then
         metric="-w"
         field="cswch"
         title="Context switches/second"
 
-elif [[ $1 == "iowait" ]]
+elif [[ $metric == "iowait" ]]
 then
-	metric="-u"
-	field="iowait"
-	title="Context switches/second"
+ metric="-u"
+ field="iowait"
+ title="Context switches/second"
 
 
 # Failback to CPU %idle if nothing defined
-elif [[ $1 == "cpu" || $# -eq 0 ]]
+elif [[ $metric == "cpu" || $# -eq 0 ]]
 then
         metric="-u"
         field="%idle"
@@ -91,8 +119,7 @@ fi
 
 TMPFILE=`mktemp /tmp/sarplot.XXXXXXXXXX`
 
-/usr/bin/sadf -- $metric | awk "/$field/ {print \$3,\$6}" > $TMPFILE
-
+/usr/bin/sadf $safile -- $metric | awk "/$field/ {print \$3,\$6}" > $TMPFILE
 echo "set terminal dumb;
 set title '$title';
 set xdata time;
